# Generated by Django 2.1 on 2018-08-19 06:41

from django.db import migrations, models
import mainapp.utils.model_utils


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0053_reliefcampdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='image',
            field=models.ImageField(blank=True, upload_to=mainapp.utils.model_utils.upload_to),
        ),
        migrations.AlterField(
            model_name='announcements',
            name='upload',
            field=models.FileField(blank=True, upload_to=mainapp.utils.model_utils.upload_to),
        ),
    ]
