# Generated by Django 2.2.11 on 2020-06-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0112_auto_20200531_2242"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hashtag",
            name="name",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
